In [5]:
import pandas as pd 
from deepfake_detection.defaults import TEST_OUT_PATH

In [6]:
test_results_file = "with_validation_loss_b4.csv"

In [11]:
test_df = pd.read_csv(TEST_OUT_PATH / test_results_file)

In [13]:
ground_truth = test_df['ground_truth'].to_numpy()
predictions = test_df['predictions'].to_numpy()

In [14]:
ground_truth

array([1., 1., 1., ..., 1., 0., 0.])

In [15]:
predictions

array([0.99979669, 0.99983895, 0.99990153, ..., 0.88916403, 0.18580547,
       0.05718737])

In [68]:
THRESHOLD = 0.98

In [69]:
predictions = predictions > THRESHOLD

In [70]:
ground_truth = ground_truth == 1

In [71]:
ground_truth

array([ True,  True,  True, ...,  True, False, False])

In [72]:
predictions

array([ True,  True,  True, ...,  True,  True, False])

In [73]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

In [74]:
accuracy = accuracy_score(ground_truth, predictions)
precision = precision_score(ground_truth, predictions)
recall = recall_score(ground_truth, predictions)
f1 = f1_score(ground_truth, predictions)

In [78]:
print(f"Accuracy: {accuracy}, Precision: {precision}, Recall: {recall}, F1: {f1}")

Accuracy: 0.8828442563617128, Precision: 0.844414180182411, Recall: 0.9790420594286808, F1: 0.9067582539330823
